config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :computers
  resources :charges
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations'}
  root 'computers#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/computer.rb
class Computer < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    belongs_to :user, optional: true
    has_many :line_items
    mount_uploader :image, ImageUploader
    include PgSearch
    

    validates :title, :price, presence: true
    validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed." }
    
    scope :sorted, ->{ order(title: :asc) }

    pg_search_scope :search,
                    against: [
                      :title,
                      :description,
                      :grpahics_card
                    ],
                    using: {
                      tsearch: {
                        prefix: true,
                        normalization: 2
                      }
                    }
  
    def self.perform_search(keyword)
      if keyword.present?
      then Computer.search(keyword)
      else Computer.all
      end.sorted
    end
  


    CASE = %w{ NZXT Cooler_Master Corsair Phanteks }
    MOTHERBOARD = %w{ EVGA ASRock ASUS MSI Gigabyte}
    POWERSUPPLY = %w{ Antec EVGA Corsair XFX }
    GPU = %w{ Gigabyte_GTX_1080 NVIDIA_GTX_1080 ASUS_Radeon_RX_580 MSI_RX_VEGA_64}
    CPU = %w{ Intel_Core_i7-8700K AMD_Ryzen_2600 AMD_Threadripper_1950X Intel_Core_i9-7900X}
    HARDDRIVE = %w{ Samsung_860_Pro  Seagate_Barracuda_7200 Crucial_MX500}
    MEMORY = %w{ Corsair Vengeance  GSkill Ripjaws  Kingston HyperX Fury }
    FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
    
    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "Line items present")
            throw :abort
    end
end
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_computer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /computers
  # GET /computers.json
  def index
    #@computers = Computer.all

        if params[:search].present?
          @computers = Computer.perform_search(params[:search])
        else
          @computers = Computer.all
        end
      end

  

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
    #@computer = current_user.computers.build
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers
  # POST /computers.json
  def create
    # @computer = current_user.computers.build(computer_params)
    @computer = Computer.new(computer_params)
    @computer.user_id = current_user.id
    logger.debug("111111111")
    logger.debug(@computer)
    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computer was successfully created.' }
        format.json { render :show, status: :created, location: @computer }
      else
        format.html { render :new }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to @computer, notice: 'Computer was successfully updated.' }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url, notice: 'Computer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit(:title, :price, :description, :finish, :case, :motherboard, :power_supply, :grpahics_card, :cpu, :ram, :hardrive, :image)
    end
end

app/helpers/computers_helper.rb
module ComputersHelper

    def computer_author(computer)
        user_signed_in? && current_user.id == computer.user.id
    end
        
end

app/views/computers/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @computer, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, placeholder: "0.00", required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

      

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-3">
            <div class="control">
              <label class="label">CPU</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :central_processing_unit, collection: Computer::CPU, prompt: "Select CPU" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-3">
            <div class="control">
              <label class="label">Finish</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :finish, collection: Computer::FINISH, prompt: "Select finish" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-3">
            <div class="control">
              <label class="label">GPU</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :grpahics_card, collection: Computer::GPU, prompt: "Select GPU" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
       

         <div class="field column is-3">
            <div class="control">
              <label class="label">Case</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :case, collection: Computer::CASE, prompt: "Select Case" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
           </div>
           
<div class="columns">
           <div class="field column is-3">
            <div class="control">
              <label class="label">MotherBoard</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :motherboard, collection: Computer::MOTHERBOARD, prompt: "Select Motherboard" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

           <div class="field column is-3">
            <div class="control">
              <label class="label">Power Supply</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :power_supply, collection: Computer::POWERSUPPLY, prompt: "Select finish" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

           <div class="field column is-3">
            <div class="control">
              <label class="label">Memory</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :memory, collection: Computer::MEMORY, prompt: "Select memory" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

           <div class="field column is-3">
            <div class="control">
              <label class="label">Storage</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :hard_drive, collection: Computer::HARDDRIVE, prompt: "Select storage" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
           </div>
           

      

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input computer-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', computers_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>





<!--OLD FORM BEFORE UPDATE REMOVED MODEL FROM OPTIONS>
  <div class="field">
          <div class="control">
            <%#= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div-->

app/views/computers/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Computer
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', computer: @computer %>
</div>

<!--Old form-->
<%#= render 'form', computer: @computer %>

<%#= link_to 'Show', @computer %> 
<%#= link_to 'Back', computers_path %>

app/views/computers/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest Computers on Lazerus
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="computer-index-grid pt4">
  <% @computers.each do |computer| %>

    <div class="computer border-light">
      <div class="computer-thumb">
      <%= link_to image_tag(computer.image_url(:thumb)), computer %>

      <% if computer.finish? %>
        <div class="condition">
          <span class="tag is-dark"><%= computer.finish %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to computer.title, computer %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= computer.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(computer.price) %></p>

      <% if computer_author(computer) %>
         <%= link_to 'Edit', edit_computer_path(computer), class: "button is-small" %>
         <%= link_to 'Delete', computer, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/computers/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell a Computer
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', computer: @computer %>
</div>

<!--OLD form-->

<%#= render 'form', computer: @computer %>

<%#= link_to 'Back', computers_path %>

app/views/computers/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section computer-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @computer.title %></h1>

      <div class="feature-image">
        <%= image_tag(@computer.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @computer.description %>


      <h3 class="subtitle is-4 pt5">Product Specs</h3>

      <table class="table is-narrow">
        <% if @computer.finish %>
        <tr>
          <td class="has-text-weight-bold">Finish:</td>
          <td><%= @computer.finish %></td>
        </tr>
        <% end %>

        <% if @computer.case %>
          <tr>
            <td class="has-text-weight-bold">Case:</td>
            <td><%= @computer.case %></td>
          </tr>
        <% end %>

        <% if @computer.memory %>
          <tr>
            <td class="has-text-weight-bold">RAM:</td>
            <td><%= @computer.memory %></td>
          </tr>
        <% end %>

      <% if @computer.hard_drive %>
        <tr>
          <td class="has-text-weight-bold">Storage:</td>
          <td><%= @computer.hard_drive %></td>
        </tr>
          <% end %>

        <% if @computer.grpahics_card %>
          <tr>
            <td class="has-text-weight-bold">GPU:</td>
            <td><%= @computer.grpahics_card %></td>
          </tr>
        <% end %>

        <% if @computer.central_processing_unit %>
          <tr>
            <td class="has-text-weight-bold">CPU:</td>
            <td><%= @computer.central_processing_unit %></td>
          </tr>
        <% end %>

        <% if @computer.motherboard %>
          <tr>
            <td class="has-text-weight-bold">Motherboard:</td>
            <td><%= @computer.motherboard %></td>
          </tr>
        <% end %>

        <% if @computer.power_supply %>
          <tr>
            <td class="has-text-weight-bold">Power Supply:</td>
            <td><%= @computer.power_supply %></td>
          </tr>
        <% end %>

      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@computer.price) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @computer.user.name %></p>
        <%= button_to 'Add to cart', line_items_path(computer_id: @computer), class: 'button is-warning add-to-cart center' %>
      </div>
    </div>
  </div>

  <% if computer_author(@computer) %>
    <%= link_to 'Edit', edit_computer_path(@computer), class: 'button' %>
  <% end %>
</section>